name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: |
        make install-dev
    - name: Run ruff
      run: |
        make lint
